spring:
  datasource:
    # url: ${SPRING_DATASOURCE_URL}
    # username: ${SPRING_DATASOURCE_USERNAME}
    # password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:mysql://localhost:3306/capstonebase
    username: joseph
    password: Jos@ph
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

Stripe:
  apiKey: sk_test_51O4KdzSGBkDtFnqjpMM9VOqGATQKElJqujUcjFEwVIDV0JIDUyM9TXRlVdK4o5pJhwQl7sH6n9SWg5a1YUUU8BFy00dkKiuOfa
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
file:
  path: /home/joseph/final/customer_details.pdf
